export const measurements = [
  {
    email: "john.doe@example.com",
    gender: "male",
    unit: "cm",
    measurements: {
      shoulderToShoulderLength: 45,
      highBustCircle: 95,
      bustCircle: 98,
      bustTipsLength: 20,
      shoulderToBicepsLength: 22,
      shoulderToElbowLength: 35,
      shoulderToWristLength: 60,
      wristCircle: 17,
      neckCircle: 38,
      bicepsCircle: 32,
      shoulderArmpitCircle: 42,
      hipCircle: 96,
      waistCircle: 85,
      neckToShoulderLength: 12,
      neckToBustLength: 28,
      neckToBustToWaistLength: 45,
      centerBackLength: 42,
      crossBackLength: 38,
      riseLength: 28,
      ankleCircle: 24,
      waistToAnkleLength: 105,
      thighCircle: 58,
      inseamLength: 78,
      outseamLength: 102,
      elbowCircle: 27,
      kneeCircle: 38,
      waistToKneeLength: 55,
      calfCircle: 36,
      headCircle: 57,
      heightLength: 175,
    },
  },
  {
    email: "jane.smith@example.com",
    gender: "female",
    unit: "cm",
    measurements: {
      shoulderToShoulderLength: 38,
      highBustCircle: 85,
      bustCircle: 90,
      bustTipsLength: 18,
      shoulderToBicepsLength: 20,
      shoulderToElbowLength: 32,
      shoulderToWristLength: 55,
      wristCircle: 15,
      neckCircle: 33,
      bicepsCircle: 28,
      shoulderArmpitCircle: 38,
      hipCircle: 95,
      waistCircle: 70,
      neckToShoulderLength: 10,
      neckToBustLength: 25,
      neckToBustToWaistLength: 40,
      centerBackLength: 40,
      crossBackLength: 35,
      riseLength: 25,
      ankleCircle: 22,
      waistToAnkleLength: 100,
      thighCircle: 52,
      inseamLength: 75,
      outseamLength: 98,
      elbowCircle: 24,
      kneeCircle: 35,
      waistToKneeLength: 52,
      calfCircle: 34,
      headCircle: 54,
      heightLength: 165,
    },
  },
  {
    email: "alex.johnson@example.com",
    gender: "other",
    unit: "inch",
    measurements: {
      shoulderToShoulderLength: 17,
      highBustCircle: 36,
      bustCircle: 38,
      neckCircle: 15,
      waistCircle: 32,
      hipCircle: 40,
      heightLength: 68,
    },
  },
];
